#version: '3.9'
services:
  zookeeper:
      image: confluentinc/cp-zookeeper:latest
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - kafka_data:/bitnami/kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: sample
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

#db
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: elevate
      POSTGRES_PASSWORD: elevate
      POSTGRES_DB: ordersAndInventory
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin_container
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_CONFIG_PROXY_X_HOST_COUNT: 1
        PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: 1
        PGADMIN_CONFIG_SERVER_MODE: 'True'
      ports:
        - "9090:80" #this is different from default 8080
      depends_on:
        - postgres
      volumes:
        - pgadmin_data:/var/lib/pgadmin
#elixir app 
  # app:
  #   build: 
  #     context: .
  #     #dockerfile: Dockerfile
  #   depends_on:
  #     - kafka
  #     - postgres
  #   environment:
  #     KAFKA_HOST: kafka
  #     KAFKA_PORT: 9092
  #     DB_HOST: postgres
  #     DB_USER: user
  #     DB_PASS: password
  #     DB_NAME: dbname
volumes:
  kafka_data:
    driver: local
  postgres_data:
  pgadmin_data:

